# Generated by Django 4.1.4 on 2022-12-21 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('Payment_date', models.DateField()),
                ('Expiration_date', models.DateField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='payments.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expired_payments',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Penalty_fee_amount', models.FloatField()),
                ('Payment_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagosusuarios', to='payments.payment_users')),
            ],
        ),
    ]
